version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - docs

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
